baseURL = "https://maurofaccin.github.io"
title = "Mauro Faccin"
relativeURLs = "true"
canonifyurls = true
disablePathToLower = true

languageCode = "en-us"
DefaultContentLanguage = "en"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.fr]
    languageName = "Français"
    weight = 2

[blackfriday]
   plainIDAnchors = true
   hrefTargetBlank = true

[markup]
    [markup.goldmark]
        [markup.goldmark.extensions]
            definitionList = true
            footnote = true
            linkify = true
            strikethrough = true
            table = true
            taskList = true
            typographer = true
        [markup.goldmark.renderer]
            unsafe = true

[[menu.main]]
  name = "Publications"
  identifier = "pubs"
  url = "/papers/"
  weight = 110
[[menu.main]]
  name = "Slides & Posters"
  identifier = "slides"
  url = "/slides/"
  weight = 110
[[menu.main]]
  name = "Codes"
  identifier = "codes"
  url = "/codes/"
  weight = 111
[[menu.main]]
  name = "Curriculum Vitæ"
  identifier = "cv"
  url = "/cv/"
  weight = 112
[[menu.main]]
  name = "Contacts"
  identifier = "contacts"
  url = "/contacts/"
  weight = 113
