base_url = "https://maurofaccin.github.io"
title = "Mauro Faccin"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
external_links_target_blank = false
smart_punctuation = false

[extra]
# Put all your custom variables here

van = [
    "/papers",
    "/slides",
    "/codes",
    "/cv",
    "/contacts"
]

[extra.nav]
Publications = "/papers"
"Slides & Posters" = "/slides"
Codes = "/codes"
"Curriculum Vitæ" = "/cv"
Contacts = "/contacts"
